### ISSUE TITLE
Incorporate pprof HTTP debugging handler.

### ISSUE THREAD

**Issue by jordy1024** [megaease/easeprobe#104]
This registers the pprof debugging handler via the middleware documented in https://pkg.go.dev/github.com/go-chi/chi/middleware#Profiler.

```
r.Mount("/debug", middleware.Profiler())
```

some issues about  `middleware.Profiler()`: https://github.com/go-chi/chi/issues/262

**Comment by jordy1024** [comment]
work in progress

**Comment by thinhlh** [comment]
This is still open
Can not use both `CleanPath` & `Profiler` at the same time
```
router.Use(middleware.CleanPath)
router.Mount("/debug", middleware.Profiler())
```

**Comment by samanhappy** [comment]
Hi @thinhlh, this issue is quite outdated, and the codes referenced have been altered. Could you please detail the problem you encountered? Additionally, it would be helpful if you could provide some context, as both the code and the team have likely seen some changes.
