### ISSUE TITLE
HTTP Probe Configuration  能添加个proxy吗？

### ISSUE THREAD

**Issue by triumph** [megaease/easeprobe#176]
大大好，
在配置  HTTP Probe Configuration 的时候， 我们有个别内网页面，是需要通过指定的代理才能访问的， 
不晓得 大大能有时间给  HTTP Probe Configuration 探活功能，添加个 指定代理的功能吗？（比如 http代理）。

**Comment by triumph** [comment]
如果，可能的话， 还能给  HTTP Probe Configuration 探活功能，添加个 修改User-Agent 的功能吗？（我们个别页面，是指定User-Agent才能访问）。

**Comment by haoel** [comment]
PR #177 will address this issue.
