### ISSUE TITLE
build Error on mac 

### ISSUE THREAD

**Issue by killua525** [megaease/easeprobe#181]
commit: a1126c2
os:
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79

```
make
mkdir -p /private/tmp/easeprobe//build/bin
go mod tidy
CGO_ENABLED=0 go build -a -ldflags '-s -w -extldflags "-static"' -gcflags=-G=3 -o /private/tmp/easeprobe//build/bin/easeprobe /private/tmp/easeprobe/cmd/easeprobe
directory /private/tmp/easeprobe/cmd/easeprobe outside main module or its selected dependencies
make: *** [/private/tmp/easeprobe//build/bin/easeprobe] Error 1
```

**Comment by killua525** [comment]
` RELEASE_DIR := ${MKFILE_DIR}/build/bin` ->  `./build/bin` ?

**Comment by haoel** [comment]
@killua525 just a quick question - why do you check out the EaseProbe into /tmp directory? this directory would be clean by the system periodically.

Please check out the code into the regular directory. 

Thanks.

**Comment by killua525** [comment]
Move the folder to home and is work. Thx a lot
