### ISSUE TITLE
能给 TLS Probe Configuration 加上  http proxy 和 自定义 useragent 吗？  谢谢

### ISSUE THREAD

**Issue by triumph** [megaease/easeprobe#193]
大大好
      能给 TLS Probe Configuration 加上  http proxy 和 自定义 useragent 吗？ 就和之前的 http Probe Configuration一样， 不知道方便添加不，辛苦，各位大大了。 我们只能享受福利了。

**Comment by haoel** [comment]
the User-Agent belongs to HTTP, not TLS.  and I think the proxy for TLS could be considered.
