### ISSUE TITLE
If there are many sites, can I include conf files like nginx?

### ISSUE THREAD

**Issue by feeops** [megaease/easeprobe#201]
If there are many sites
For example, thousands of sites, all written in a config.yaml is too long and ugly

Can you include conf files like nginx?
That is, include files in a directory to make it easier to distinguish

**Comment by haoel** [comment]
sorry,  currently, the YAML does not include any kind of "import" or "include" statement.

and I think we can support the multiple yaml files. but I need time to think how to implement it.,

**Comment by haoel** [comment]
P.S. I need to evaluate these two solutions: 1) develop a YAML editor UI, 2) support the multiple YAML files

the first one would address the pains of YAML configuration much more than the second one, but the work efforts are much more.

**Comment by feeops** [comment]
> P.S. I need to evaluate these two solutions: 1) develop a YAML editor UI, 2) support the multiple YAML files
> 
> the first one would address the pains of YAML configuration much more than the second one, but the work efforts are much more.

知名时序数据库VictoriaMetrics是采用后者，可以加载多个yaml文件
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/vmagent.md#loading-scrape-configs-from-multiple-files

**Comment by haoel** [comment]
> > P.S. I need to evaluate these two solutions: 1) develop a YAML editor UI, 2) support the multiple YAML files
> 
> > 
> 
> > the first one would address the pains of YAML configuration much more than the second one, but the work efforts are much more.
> 
> 
> 
> 知名时序数据库VictoriaMetrics是采用后者，可以加载多个yaml文件
> 
> https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/vmagent.md#loading-scrape-configs-from-multiple-files

Would you like to contribute this PR?

**Comment by feeops** [comment]
> 

Sorry.My program skill is not good enough.

**Comment by yafengstark** [comment]
> 
I can hava a try. Give me some time, Please.
