### ISSUE TITLE
Module-wise installation?

### ISSUE THREAD

**Issue by chainhead** [megaease/easeprobe#212]
**Background & X Problem**
Selective installation to reduce container image.

**Proposal and Expectation**
Is it possible to install only a given set of probes and notifiers? For example, I want to monitor MySQL database with the notification to be sent to Slack and Teams. Such an installation will reduce container image resulting in efficient deployment.

**Solutions & Y Problems**
I am not a Go developer. However, I would expect a `config.yaml` key for `probes` and `notifiers` that are arrays for the chosen probes and notifiers. Or, at least, instructions for custom build that can pick specific probes and notifiers would be helpful.

**Additional context**
None.

**Comment by haoel** [comment]
@chainhead Thanks for raising this issue.

And it's hard to select the particular module to compile, but maybe we can find a way to reduce the size of the docker image.

may I know the size of the container image you think is fine? and why do you concern about the size?  as the current EaseProbe's binary size is not big.

**Comment by chainhead** [comment]
> And it's hard to select the particular module to compile, but maybe we can find a way to reduce the size of the docker image.

Thanks for attempting! Out of curiosity, how do you then plan to add more modules - topics or notifiers - in the future?

> may I know the size of the container image you think is fine? 

A rule of thumb I use is 100 MB to 300 MB of image size. By no means, this estimate is "golden".

**Comment by haoel** [comment]
The  current size of the latest version is much smaller than 100MB

- For  the docker image, the EaseProbe image on [Docker Hub](https://hub.docker.com/r/megaease/easeprobe/tags) is just 15MB, 
- For the [Release Binary](https://github.com/megaease/easeprobe/releases), the EaseProbe is just  7MB - 8MB

In the future, we will keep our principle and make sure the EaseProbe is lightweight & standalone, so don't worry about the size.
