### ISSUE TITLE
Golang monkey patching library utilized against terms of license

### ISSUE THREAD

**Issue by mattlorimor** [megaease/easeprobe#216]
The Golang monkey patching library, https://github.com/bouk/monkey, is being utilized directly against [its license](https://github.com/bouk/monkey/blob/master/LICENSE.md):

> Copyright Bouke van der Bijl
> 
> I do not give anyone permissions to use this tool for any purpose. Don't use it.
> 
> I’m not interested in changing this license. Please don’t ask.

It is also archived and not maintained.

**Comment by haoel** [comment]
Thanks for reporting this issue.

These library codes are just used for unit testing, which is not included in the release.

But we should find an alternative or just write our own monkey patching library.

P.S. there is a discussion you can refer to https://news.ycombinator.com/item?id=28263721

**Comment by haoel** [comment]
close this issue temporarily as this is a known issue, and we don't have a solution at this moment. I will keep my eyes open if there is an alternative solution.
