### ISSUE TITLE
failure/success threshold before sending notifications

### ISSUE THREAD

**Issue by zhzy0077** [megaease/easeprobe#230]
**Background & X Problem**
It's easy to have false postitives when looking at CPUs/latencies. For example, CPU might have a peak at 80%+ but just for a few seconds.

**Proposal and Expectation**
Just like failure-threshold in https://github.com/TwiN/gatus, it's handy if I'm allowed to set the threshold before sending notifications.

**Comment by haoel** [comment]
just want to confirm the requirement, and be more specific.

the requirement is 

    with the latest `n` times probe, there are `m` times failures, then we send the failure notification. ( n>=m )

so, when n==m, it means

    only we continuously meet the `n` times failures, then we send the failure notification.

**Comment by zhzy0077** [comment]
the threshold in gatus works in this way:
- failure-threshold: the failure notification will be sent if there're `n` continues failures.
- success-threshold: once there're `n` continues success event, the resolved noticiation will be sent.

I have no concern on your proposal. To me, a simple N is good enough.

**Comment by haoel** [comment]
All right, I will work on my proposal. that's would be flexible.

**Comment by haoel** [comment]
after deep thinking, I think using `m/n` would make things complicated.  for example, if we configure  2/3 for failure and  1/1 for success, it would be failure or success at the same time. This would introduce ambiguity.

I think just using the continuous `n`  times failure/success would be clear.

**Comment by haoel** [comment]
@zhzy0077  the PR is ready to review, please feel free to review it.
