### ISSUE TITLE
EASEPROBE_TIME is only provided in JSON format

### ISSUE THREAD

**Issue by zhzy0077** [megaease/easeprobe#231]
**Environment (please complete the following information):**
 - OS: Linux VM-8-5-centos 3.10.0-1160.76.1.el7.x86_64 # 1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - EaseProbe Version EaseProbe v1.7.0 @ a4255478e017

**Describe the bug**
When looking at shell notification script, values are both provided by JSON format or env variables, however they're misaligned. `EASEPROBE_TIME` is part of JSON format but not in env variables.

**To Reproduce**
1. set shell script as https://github.com/megaease/easeprobe/blob/main/resources/scripts/notify/notify.sh
2. see output

**Expected behavior**
`EASEPROBE_TIME` env variable should also exist.

The reason I need this is because, the docker image was built based on alpine so there's quite a little utitlites avaiable out of box, so I cannot run `jq` without a self-made image. `EASEPROBE_TIMESTAMP` is in env variable but it's a millisecond epoch so `date -d` is not able to calc it unless I do the math first.

**Comment by zhzy0077** [comment]
I think it's really a simple change. If you guys think it's the right approach, I can send the PR.

**Comment by haoel** [comment]
No problem. Welcome to contribute to this PR.
