### ISSUE TITLE
Native Postgresql connection without ssl enabled

### ISSUE THREAD

**Issue by jenggo** [megaease/easeprobe#285]
I've following manual on how to config native probe for postgresql (https://github.com/megaease/easeprobe/blob/main/docs/Manual.md#78-native-client-probe-configuration)

here's my code:

```
client:
  - name: Posgresql
    driver: postgres
    host: postgis:5432
    username: xxxxx
    password: xxxxx

  - name: Pgbouncer
    driver: postgres
    host: pgbouncer:5432
    username: xxxxxx
    password: xxxxxx
```

and here's report:
```
Posgresql Failure ❌
postgis:5432 - ⏱ 4ms
Error (client/postgres): pgdriver: SSL is not enabled on the server
> EaseProbe v2.0.0 @ c0d124fc3faa at 2023-02-10 10:49:53 UTC

Pgbouncer Failure ❌
pgbouncer:5432 - ⏱ 2ms
Error (client/postgres): pgdriver: SSL is not enabled on the server
> EaseProbe v2.0.0 @ c0d124fc3faa at 2023-02-10 10:49:54 UTC
```

i'm using docker deployment method

**Comment by haoel** [comment]
Thanks for reporting this issue, I can reproduce this problem, I will give a fix as soon as I can.

**Comment by haoel** [comment]
@jenggo To get the patch, you need to check out the latest code to build the binary by yourself. let me know if it works, otherwise please reopen this issue. thanks for understanding.

**Comment by jenggo** [comment]
confirmed 👍
