### ISSUE TITLE
How to support multiple configuration files

### ISSUE THREAD

**Issue by fsckzy** [megaease/easeprobe#293]
The config file looks ugly when I have a lot of targets to probe。
I saw in this [issue](https://github.com/megaease/easeprobe/issues/201) that this function seems to have been supported, but I didn’t see any relevant introductions in the user documentation or configuration file samples. If it is already supported, can you mention it in the documentation?

**Comment by oewang** [comment]
The answer can be found in the README.md file, under the heading Run.

**Comment by fsckzy** [comment]
> 答案可以在标题下的 README.md 文件中找到。`2.3 Run`

thanks
