### ISSUE TITLE
Adding a helm repository returns 404

### ISSUE THREAD

**Issue by DpoBoceka** [megaease/easeprobe#306]
**Describe the bug**
The [helm repository](https://github.com/megaease/easeprobe/tree/main/helm/easeprobe#from-repo) seems to be invalid

```
> helm repo add easeprobe https://megaease.github.io/easeprobe
Error: looks like "https://megaease.github.io/easeprobe" is not a valid chart repository or cannot be reached: failed to fetch https://megaease.github.io/easeprobe/index.yaml : 404 Not Found

```

**Comment by samanhappy** [comment]
Thanks for reporting this issue,  it looks like that the Helm repository is not deployed proberly, we will fix it as soon as possible.

**Comment by samanhappy** [comment]
@DpoBoceka we just release a Helm Chart version, you can try again and tell us if the problem still exists.
Also note to use the new install command below because the original repository is wrong
`helm install [RELEASE_NAME] easeprobe/easeprobe`

**Comment by DpoBoceka** [comment]
yeah, it works! Thanks for fixing it so rapidly :)

**Comment by DpoBoceka** [comment]
Although there's a failed run against main branch https://github.com/megaease/easeprobe/actions/runs/4383690556/jobs/7674244056

**Comment by samanhappy** [comment]
yeal, we are optimising the helm release name to avoid making our users confused, please hold on and we will notice you first time when it is ready.

**Comment by samanhappy** [comment]
@DpoBoceka the new release is ready now, you can try it again when you hava time.

**Comment by DpoBoceka** [comment]
all good!
