### ISSUE TITLE
Questions about the Channel example in the user manual title 4

### ISSUE THREAD

**Issue by oewang** [megaease/easeprobe#344]
**Describe the bug**
- I didn't understand the example of the user manual title 4 about the channel.
- I think the following diagram is correct,I'm not sure if I understand it correctly.
![channel-example](https://user-images.githubusercontent.com/18392486/236618502-d4c78866-1fd1-470b-973b-378eb1ec70f9.svg)

**Comment by haoel** [comment]
The example in manual is incorrect, I will fix that. And your understanding here is correct!

**Comment by oewang** [comment]
I reviewed this material, but I noticed you didn't edit it, did you not see my comment?
![image](https://user-images.githubusercontent.com/18392486/236655262-35d2efd0-c6f2-454c-a6b9-da4d1697440c.png)

**Comment by haoel** [comment]
it's pending, you should push your comment.
