### ISSUE TITLE
Questions about using the unified disable symbol

### ISSUE THREAD

**Issue by oewang** [megaease/easeprobe#345]
**Describe the bug**
1. Code documentation description error：
    - In line 129 of the config.go file, the description attribute of the PIDFile field does not match the documentation description.

2. About SLA data persistence and PID file disable configuration and other disable configuration, what symbol to use to indicate the problem：
    - I think we can use "-" to unify the symbols, a unified symbol identifier will reduce the user error rate and make it easier to use.

**Comment by haoel** [comment]
- for PIDFile document I fix it in #346 
- for PIDFile and SLA data, using `-` to disable them
- for Application Log & Access Log, you cannot disable them, if you don't configure the file path, it would be log into stdout.

**Comment by oewang** [comment]
- Pid file using `-` to disable them, I think [this line of code](https://github.com/megaease/easeprobe/blob/9ff1722a9ad4c5ec6f08c5e50f2cd44f7995a023/cmd/easeprobe/main.go#L105) should be changed to look like this：
```golang
if strings.TrimSpace(c.Settings.PIDFile) != "-" {
  // create pid file
} else {
  // don't create pid file
}
```

**Comment by haoel** [comment]
You're absolutely right!

instead fix this in code, I'd like to correct the document. as the code change could introduce the compatibility issue.

Thanks for pointing this out.

**Comment by haoel** [comment]
@oewang if you have time please help to review the associated PR.

**Comment by oewang** [comment]
Ok, Please give me permission to review the code

**Comment by oewang** [comment]
> @oewang if you have time please help to review the associated PR.

Ok, Please give me permission to review the code

**Comment by oewang** [comment]
> You're absolutely right!
> 
> instead fix this in code, I'd like to correct the document. as the code change could introduce the compatibility issue.
> 
> Thanks for pointing this out.

maybe you can be compatible with it.

**Comment by haoel** [comment]
> > @oewang if you have time please help to review the associated PR.
> 
> Ok, Please give me permission to review the code

You can just simply write your review comment in that PR. 

And I can give your the collaboration permission after you do some code contributions.

> maybe you can be compatible with it.

OK, I think you are right.

**Comment by oewang** [comment]
> > > @oewang if you have time please help to review the associated PR.
> > 
> > 
> > Ok, Please give me permission to review the code
> 
> You can just simply write your review comment in that PR.
> 
> And I can give your the collaboration permission after you do some code contributions.
> 
> > maybe you can be compatible with it.
> 
> OK, I think you are right.

Okay, I think there are no more problems. 
If there is a bug or an idea next time, maybe I can do a code commit.

**Comment by haoel** [comment]
@oewang if you are fine, please help to approve the pr

**Comment by oewang** [comment]
> @oewang if you are fine, please help to approve the pr
Ok, I approve the commit.
