### ISSUE TITLE
Telegram SLA Notification "message is too long"

### ISSUE THREAD

**Issue by jenggo** [megaease/easeprobe#364]
**Background & X Problem**
Some of my servers do not report the SLA, so when I check the log, it turns out there is `Overall SLA Report([telegram / OneOfMyServer / SLA] failed after 3 retries - Error response from Telegram - code [400] - msg [{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: message is too long\"}]) - failed to send!`

**Proposal and Expectation**
Can you cut the message into several parts?

**Solutions & Y Problems**
I think it's because of the telegram limitation, can't send more than 4096 characters?
![2023-06-11_08-03](https://github.com/megaease/easeprobe/assets/174442/6e034e9f-b840-479f-9fda-6ef477f5a1a4)

**Comment by samanhappy** [comment]
@jenggo thanks for reporting, it should be a limitation from Telegram as you mentioned, cutting message sounds like a reasonable solution, we will try it and notice you when it is completed.

**Comment by samanhappy** [comment]
@jenggo we have completed a PR to split message for Telegram, you can test it using latest code now.

**Comment by jenggo** [comment]
![2023-06-14_07-35](https://github.com/megaease/easeprobe/assets/174442/66ae0c45-eb29-41f6-86f0-aee50b23d4f4)
confirmed, thank you
