### ISSUE TITLE
update the email address 

### ISSUE THREAD

**Issue by xiaomao87** [megaease/easeprobe#366]
can help me update the history commit author mail address ?

commit: 882a021b6752b1fa5ca032bb57d4aa1f9142747b

old: xiaomao87 <111742842+xiaomao87@users.noreply.github.com>

want: xiaomao87 <maoshuai@163.com>

**Comment by samanhappy** [comment]
changing commit author is not easy because it may rewrites commit history, may I know why do you want to change it?

**Comment by xiaomao87** [comment]
> changing commit author is not easy because it may rewrites commit history, may I know why do you want to change it?

Submitted pr to other projects only to discover the use of anonymous email 。。。

**Comment by samanhappy** [comment]
is the anonymous email displayed in new commits or just old commits?
if just old, then I think it is not so important because someone can find you from github ID if necessary

**Comment by xiaomao87** [comment]
> is the anonymous email displayed in new commits or just old commits? if just old, then I think it is not so important because someone can find you from github ID if necessary

OK，thks
