### ISSUE TITLE
tls cert expiration not working as expect when visit url redirected

### ISSUE THREAD

**Issue by czyt** [megaease/easeprobe#367]
I have a domain `test.xyz.tech`,when visit without any querystring or sub url,it will be redireted to the website root dir of `main.xyz.tech` which has an expired cert,so when I setup a tls expiration to check `test.xyz.tech:443` it will check  `main.xyz.tech` cert not the `test.xyz.tech`.

**Comment by localvar** [comment]
hi @czyt , redirect is concept of HTTP but not TLS, that why tls expiration check didn't work for redirection.
why not setup a tls check for `main.xyz.tech`?

**Comment by czyt** [comment]
> hi @czyt , redirect is concept of HTTP but not TLS, that why tls expiration check didn't work for redirection. why not setup a tls check for `main.xyz.tech`?

i have also setted up a http check,and set `insecurity:false` option to check for https,but still get the same cert check failed for server `test.xyz.tech` which has a valid cert in fact @localvar

**Comment by localvar** [comment]
@czyt could you please put your full configuration here?

**Comment by czyt** [comment]
> @czyt could you please put your full configuration here?

sorry about this,it's a production env config.so I am sorry for not providering it.
