### ISSUE TITLE
Is it possible not to send the report?

### ISSUE THREAD

**Issue by fsckzy** [megaease/easeprobe#380]
Sending a long string of characters every day will affect normal alarms？
![image](https://github.com/megaease/easeprobe/assets/34021474/b3c87cb6-3a44-4ac8-949c-85b85d2fb567)

The configuration file is commented
![image](https://github.com/megaease/easeprobe/assets/34021474/4a7d7d01-e9d3-4323-8442-d68e0e5150d1)

**Comment by localvar** [comment]
as show in your second snapshot, you can set `schedule` to `none` to disable the report.

**Comment by fsckzy** [comment]
> as show in your second snapshot, you can set `schedule` to `none` to disable the report.

Already modified to none, no effect
![image](https://github.com/megaease/easeprobe/assets/34021474/12f648bc-246a-4beb-bddf-bb042a09fead)
![image](https://github.com/megaease/easeprobe/assets/34021474/3c5e2dd7-bb4d-495f-8c49-7612128f825e)

**Comment by samanhappy** [comment]
could you please show us your configuration file? the `sla` configuration should be below `settings` part

**Comment by samanhappy** [comment]
find your configuration content above, the right configuration shoule be
```
settings:
  sla:
    schedule: none
```

**Comment by fsckzy** [comment]
> 
Can't it?
![image](https://github.com/megaease/easeprobe/assets/34021474/e5217d6f-3600-4171-ba24-36fc9946b760)

**Comment by fsckzy** [comment]
I deleted all the sla for a period of time, and I saw the log after restarting, or will it be sent? Why?

**Comment by fsckzy** [comment]
> I deleted all the sla for a period of time, and I saw the log after restarting, or will it be sent? Why?我删除了一段时间的所有sla，重新启动后看到了日志，还是会发送？为什么？

`Jul 12 09:50:45 ansible easeprobe[160456]: time="2023-07-12T09:50:45+08:00" level=info msg="Scheduling daily SLA reports at 00:00 UTC time..."
Jul 12 09:50:45 ansible easeprobe[160456]: time="2023-07-12T09:50:45+08:00" level=info msg="The SLA report will be schedule at 2023-07-13 00:00:00 UTC"`

**Comment by samanhappy** [comment]
> find your configuration content above, the right configuration should be
> 
> ```
> settings:
>   sla:
>     schedule: none
> ```

pay attention to the indentation in YAML configuration file
