### ISSUE TITLE
Send notification to generic or custom url

### ISSUE THREAD

**Issue by 2kodes** [megaease/easeprobe#414]
**Background & X Problem**
I need to send a notification to a custom URL or channel with a request body from the result of the probe. I am unable to find this option in the notification channels available. Or maybe this option is available but not documented?

**Proposal and Expectation**
The ability to have notification channel which is a generic URL and to which a request body can be sent

**Comment by samanhappy** [comment]
Sending notifications directly to a URL is not currently supported. However, you can implement a workaround solution by utilizing a [shell command](https://github.com/megaease/easeprobe/blob/main/docs/Manual.md#212-shell). An example demonstrating this approach can be found [here](https://github.com/megaease/easeprobe/blob/main/resources/scripts/notify/notify.sh). To accomplish this, you can integrate the variables from the example with a curl command.

Additionally, I'm interested in understanding the specific purpose behind your need to send notifications to a URL. Is this related to a custom notification service or for some other unique requirement? Sharing more details about your use case would help us provide more targeted assistance.

**Comment by 2kodes** [comment]
@samanhappy 

thank you for the response. will look at using the shell command

however my usecase involves sending the notification details to a custom service which will then handle writing some logs and  dispatching alerts based on certain parameters

**Comment by wayne666** [comment]
> @samanhappy
> 
> thank you for the response. will look at using the shell command
> 
> however my usecase involves sending the notification details to a custom service which will then handle writing some logs and dispatching alerts based on certain parameters

use shell script to notify which suit your needs, it could sent the detail to custom url.

**Comment by samanhappy** [comment]
seems resolved, reopen if necessary.
