### ISSUE TITLE
Does host probe support user and password authentication?

### ISSUE THREAD

**Issue by sicunzhao** [megaease/easeprobe#440]
If yes, how to configure it? If no, is there any plan to support it

**Comment by suchen-sci** [comment]
https://github.com/megaease/easeprobe/blob/main/docs/Manual.md#122-complete-configuration please check this link, where it contains username and password for basic auth.

**Comment by sicunzhao** [comment]
config.yaml
host:
  # Servers List                                   
  servers: #                                       
    - name : est server
      host: xx.xx.xx.xx:22
      username: user1
      password: xxxxxxxx

easeprobe.log 
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

I can log in normally through ssh user1@xx.xx.xx.xx and the above password. Will the program handle the password in a special way, if the password contains some special characters, such as 1{]2}y? ((ab:c@+)de/fgh#$suk/<

**Comment by suchen-sci** [comment]
Please reopen this issue if needed.
