### ISSUE TITLE
Is it necessary to send notifications when the status changes from down to up?

### ISSUE THREAD

**Issue by godruoyi** [megaease/easeprobe#45]
Hi, when I looked at the source code I had a question.

We know that the initial state is `init`, It is currently handled here:

❌ no notification
✅ send notification

- `init` -> `up` Initial Status ❌
- `init` -> `down` ✅ 
- `up` -> `down` ✅ 
- `down` -> `up` ✅ // here
- `up` -> `down` ✅
- `down` -> `down` ❌
- `up` -> `up` ❌

So my question is do we need to send a notification when the status changes from down to up?

**Comment by haoel** [comment]
we do send the notification when the status is changed from down to up!

**Comment by godruoyi** [comment]
thank your update, I get new knowledge.

but I have a little question, If we are sending notifications when the state changes(ET), then why don't we do anything when the state changes from `init` to `up`?

**Comment by haoel** [comment]
because this is the first time, it's a special case.

**Comment by godruoyi** [comment]
okay, thank you a lot.
