### ISSUE TITLE
 Failure([lark / lark alert service / Notification] failed after 3 retries - Error response from Lark - code [19024] - msg [Key Words Not Found]) - failed to send! 

### ISSUE THREAD

**Issue by xcrossed** [megaease/easeprobe#468]
**Environment (please complete the following information):**
 - OS: [Linux: uname -a]
 Linux codebase-01 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - EaseProbe Version [e.g. v1.2.0]
v2.1.1
**Describe the bug**
lark alert service / Notification] failed after 3 retries - Error response from Lark - code [19024] - msg [Key Words Not Found]) - failed to send! 

**To Reproduce**
1. config notify lark config
2. write a  lark/feishu  webhook http url 
3. the log will print feishu server response
4. see error

**Expected behavior**
notify send success.

**Comment by samanhappy** [comment]
The `Key Words Not Found` message is returned by the Lark service, which means you must add specific keywords to the Lark bot configuration, alternatively, you can choose other mechanisms such as whitelisting or using signatures.

**Comment by xcrossed** [comment]
ok.

**Comment by suchen-sci** [comment]
It seems this issue is solved, please consider to close it when you are convenient.

**Comment by xcrossed** [comment]
time="2024-01-10T08:00:00+08:00" level=info msg="[log / log file / SLA] - Overall SLA Report - successfully sent!"
time="2024-01-10T08:00:00+08:00" level=warning msg="[lark / lark alert service / SLA] Retried to send 1/3 - Error response from Lark - code [9499] - msg [Bad Request]"
time="2024-01-10T08:00:05+08:00" level=warning msg="[lark / lark alert service / SLA] Retried to send 2/3 - Error response from Lark - code [9499] - msg [Bad Request]"
time="2024-01-10T08:00:10+08:00" level=warning msg="[lark / lark alert service / SLA] Retried to send 3/3 - Error response from Lark - code [9499] - msg [Bad Request]"
time="2024-01-10T08:00:10+08:00" level=error msg="[lark / lark alert service / SLA] - Overall SLA Report([lark / lark alert service / SLA] failed after 3 retries - Error response from Lark - code [9499] - msg [Bad Request]) - failed to send! "

**Comment by suchen-sci** [comment]
can you provide more information about this? which api of lark/feishu server you use? what setting of easeprobe you use?

9499 bad request means easeprobe send wrong requests to lark server. but to which api? what's your webhook setting?

**Comment by suchen-sci** [comment]
can you provide more information about it? what's your setting? for the information you provide now, i can't find the problem. sorry

**Comment by suchen-sci** [comment]
@xcrossed hi, please check if your problem is still there after pr #472 is merged.

**Comment by xcrossed** [comment]
> @xcrossed hi, please check if your problem is still there after pr #472 is merged.

I will try the new version 2.1.2

**Comment by xcrossed** [comment]
> @xcrossed hi, please check if your problem is still there after pr #472 is merged.

**Comment by xcrossed** [comment]
> > @xcrossed hi, please check if your problem is still there after pr #472 is merged.
the same error.

```
time="2024-01-17T08:00:00+08:00" level=info msg="[log / log file / SLA] - Overall SLA Report - successfully sent!"
time="2024-01-17T08:00:00+08:00" level=warning msg="[lark / lark alert service / SLA] Retried to send 1/3 - Error response from Lark - code [9499] - msg [Bad Request]"
time="2024-01-17T08:00:05+08:00" level=warning msg="[lark / lark alert service / SLA] Retried to send 2/3 - Error response from Lark - code [9499] - msg [Bad Request]"
time="2024-01-17T08:00:10+08:00" level=warning msg="[lark / lark alert service / SLA] Retried to send 3/3 - Error response from Lark - code [9499] - msg [Bad Request]"
time="2024-01-17T08:00:10+08:00" level=error msg="[lark / lark alert service / SLA] - Overall SLA Report([lark / lark alert service / SLA] failed after 3 retries - Error response from Lark - code [9499] - msg [Bad Request]) - failed to send! 
```

**Comment by suchen-sci** [comment]
Could you please provide the configuration content to let us test it in our local environment (make sure you mask the secret in the configuration)? 
Because we test lark and it works. By the information you provided, we can't find the problem.

**Comment by suchen-sci** [comment]
Hi, can you download the newest version of code from github and use `make` command to compile it. Then try it again? I am sure this time the error message will provide more information about it.

**Comment by xcrossed** [comment]
> Hi, can you download the newest version of code from github and use `make` command to compile it. Then try it again? I am sure this time the error message will provide more information about it.

ok i will give it a try and wait for notification

**Comment by suchen-sci** [comment]
sounds great. if no other problem, please consider to close this issue.
