### ISSUE TITLE
Feature Request: Support WorkWechat(企业微信）notify?

### ISSUE THREAD

**Issue by xiekeyi98** [megaease/easeprobe#5]
I was wondering if this could support Workwechat？
I'd like to try add it if we would like to support work wechat.

F.Y.R: 

Wechat API Doc:https://developer.work.weixin.qq.com/document/path/91770

**Comment by haoel** [comment]
I'm totally fine with this feature, and do you like to contribute to this feature?  ；-）

Meanwhile, there is a workaround solution - bind the email with your WorkWechat, and the notification email would be notified by WorkWechat. ；-）

--Hao
