### ISSUE TITLE
[Feature] Support notify to telegram bot or shell command

### ISSUE THREAD

**Issue by marcuslannister** [megaease/easeprobe#6]
If it can not support notify to telegram bot, then support notify to shell command.
Then I can use script like this [[Send message to Telegram on any SSH login - Konstantin Bogomolov | Web Developer](https://bogomolov.tech/Telegram-notification-on-SSH-login/)](https://bogomolov.tech/Telegram-notification-on-SSH-login/) for notification.

Thanks.

**Comment by haoel** [comment]
Look quite straightforward, could you please contribute to this feature?

- Hao

**Comment by marcuslannister** [comment]
I am an embedded system software engineer, I am familiar with C and know a little python, but I am not using go before.

I would like to study go and help to finish this feature, but I can not control the schedule.

**Comment by haoel** [comment]
Okay, let me arrange this requirement in next release. 

BTW, Go is so easy to learn especially for C programmer. 

-- Hao

**Comment by haoel** [comment]
@marcuslannister the telegram notification is supported, close this issue now. if you have further questions, please feel free to reopen this.

**Comment by avimar** [comment]
You might be interested in connecting with caronc/apprise to have an external app handle tons of different integrations without having to write one yourself for each. It's a python code base, though.
