### ISSUE TITLE
k8s installation? Docker image?

### ISSUE THREAD

**Issue by korjavin** [megaease/easeprobe#83]

**Comment by proditis** [comment]
Hi, can you provide some more details?

There is a docker image you can use at https://hub.docker.com/r/megaease/easeprobe by running
```
docker run -it megaease/easeprobe
```

The container expects a configuration file to be found at `/opt/config.yaml` (no default one exists)

Is this what you wanted or your request refers to something else?

**Comment by korjavin** [comment]
Yeah. Thank you!

Is there Dockerfile accessible for this built image?

**Comment by proditis** [comment]
Yes you can find it under `./resources/Dockerfile`

**Comment by korjavin** [comment]
Cool, thanks!
