### ISSUE TITLE
Accidentally started another instance of easeprobe on same host and CTRL+C didnt seem to work

### ISSUE THREAD

**Issue by proditis** [megaease/easeprobe#88]
Hi, 

I accidentally started a second easeprobe process (from a different binary / location) and after pressing ctrl+c i had to wait for a long time until the system exits.

At first i thought that it got stuck but after testing further, it exited after the initiated probes had completed first. 

During the tests, the infrastructure the easeprobe was trying to "probe" was not responsive, so i suspect this was the connection timeout that was waiting to kick-in and finish up.

I believe that the active probes should immediately stop operating once SIGINT is received, but i may overlooked something.

~Another workaround to this could be to to "release" the signal handler once the signal is received, so consecutive CTRL+C / SIGINT invocations can actually kill the process without waiting if needed?~ 

After investigating it a bit more it seems to needing bit more than just `signal.Ignore()`

**Comment by haoel** [comment]
Yes, this is the Graceful Shutdown - it needs to wait for all of the probes to finish their current work(or time out) and then exit, after that, we can exit the notification and save the probe SLA data safely.

 So, it has to wait until everything finished.

**Comment by proditis** [comment]
@haoel I understand that, but the probes started before we bind?!?! The user has to wait for the probes to complete in order to kill the application? This doesnt make sense.  

I believe this logic is not optimal. 
a) I try to kill the process immediately after start and doesnt stop, the probes at that point are meaningless
b) Why is the probe result so important at the moment we request for easeprobe to stop? I mean i understand why we dont want to loose our data but why is that particular probing SO much more important than request of the user to stop the application interactively?
c) When there are a lot of probes with varying timeouts, having to wait for them to stop makes no sense. If a probe has returned data then sure save them, if not then WHY wait?

There must be a way for admins to kill this process by SIGINT without waiting for all the probes to finish. I had to open another terminal to kill the process this goes against every logic :smiley:

**Comment by haoel** [comment]
The behavior is that we capture the signal after we start the probe and the notification, however, all of the probes are running in goroutines(non-blocking ), they all are running in parallel with the main thread. so, the program is running so quickly, and looks like they all started at the same time.  

Originally, I thought if the admin wants the process quite immediately, we can send the SIGKILL.  usually, the process management should have such behavior - kill the process, if no response, kill- 9 process. 

I think you are right that the probe result might not be important, the process is shut down, and the data lost is not a big deal.  And most of the cases for SIGINT are for Ctrl+C, sometimes, this could let the admin understand which probe stuck, but sometimes, it makes annoying. 

Besides, I just simply follow the strict rule of the graceful shutdown. Technically person. ;-) 
 
I think we can just simply remove the `signal.Notify(done, syscall.SIGINT)`   in `main()`, and only keep the SIGTERM signal capture.

Thanks for this argument!

**Comment by haoel** [comment]
@proditis I think you can do this code change!

**Comment by proditis** [comment]
That is an excellent idea, smart and simple, i love it. 

See i knew we will get to a simple solution that makes us all happy :smile: with a bit of back and forth

i am 100% with you on the fact that we must try to save the data that we currently have. 

Tested without SIGINT and worked as expected.

I tried hard to corrupt the data.yaml without success :100: 

Creating a PR
