### ISSUE TITLE
HTTP server bind already in use should cause the daemon to exit

### ISSUE THREAD

**Issue by proditis** [megaease/easeprobe#89]
When the port is already in used, easeprobe displays the following error but continues to run. 
```
ERRO[2022-05-16T00:56:00Z] [Web] HTTP server error: listen tcp 127.0.0.1:8181: bind: address already in use 
```

I believe that it would be better if we exited with a non zero status code when this happens.

**Comment by proditis** [comment]
I was thinking something like this 
```go
		if err := http.ListenAndServe(host+":"+port, r); err != nil {
			log.Errorf("[Web] HTTP server error: %s", err)
			os.Exit(-1)
		}
```

**Comment by haoel** [comment]
Yes, you find the correct place. 

However, the HTTP server is running on a go-routine,  we need a mechanism to notify the main thread the HTTP server failed and the main thread can be exited! 

I am thinking the solution now...

**Comment by proditis** [comment]
Confirmed fixed :+1:
