### ISSUE TITLE
Add version option for executable and configuration files

### ISSUE THREAD

**Issue by proditis** [megaease/easeprobe#98]
**Background & X Problem**
I wanted to performing updates between v1.4.0 and the latest version from repo on my systems, as part of the process I wanted to confirm the version of the binary but we currently have no command line option that will simply display the version. 
As it currently stands those who are interested in tracking the version somehow, have to go through checksums to the binary which is not optimal imho.

Similarly I could not determine for what version of binary my config was for.

**Proposal and Expectation**
I propose the following, 

* addition of a command line option `-v` or `-V` that will just display the version of the current binary
* addition of the version string to the displayed `Usage`
* addition of a `config.yaml` top key `version:` that will allow us to determine what version of binary this config works with
* (optionally) include a `version` key also on the `data.yaml` so that future binaries can detect older versions of the data and accommodate any potential changes that need to take place

_edit: If anyone wants to take on this please be my guest_

**Comment by haoel** [comment]
I will work on this issue.
